---
- hosts: all
  gather_facts: no

  tasks:
  - name: Actualización de VM tools
    vmware_guest_tools_upgrade:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      name: "{{  item  }}"
    delegate_to: localhost
    loop: "{{ vm_names }}"