---
- hosts: all
  gather_facts: no

  tasks:
  - name: Aumento de Recursos de VM
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      cluster: "{{ vcenter_cluster }}"
      datacenter: "{{ datacenter_name }}"
      name: "{{ vm_name }}"
      validate_certs: "false"
      folder: "{{ vm_folder }}"
      hardware:
        memory_mb: "{{ memory }}"
        num_cpus: "{{ cpu }}"
      delegate_to: "localhost"
