---
- name: Creacion de Ambiente
  hosts: all
  gather_facts: no

  tasks:
  - name: Despliegue de VMs desde template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"       # administrator@vsphere.local
      password: "{{ vcenter_password }}"
      validate_certs: no
      folder: "{{ vm_folder }}"
      name: "{{ item.vm_name }}"
      template: "{{ item.vm_template }}"
      hardware:
        memory_mb: "{{ item.memory }}"
        num_cpus: "{{ item.cpus }}"
      loop: "{{ Parametros }}"  
      delegate_to: localhost