---
- name: Obtener y Hacer Buuild en Pre-Produccion
  hosts: all
  become: yes

  tasks:
  - name: git feth
    - git:
      repo: '10.2.14.5:~/repos/cvdpwebpage.git'
      dest: /opt/cvdpwebpage

  - name: Instalar "web app"
    npm:
      name: web
      path: /app/location

  - name: Hacer de Build la aplicacion
    command: ng build {{ proyecto.name }} -c=staging --aot --vendor-chunk --common-chunk --delete-output-path --buildOptimizer --subresource-integrity

  - name: scp
    command: "scp -rv dist/browser/* ironman@{{ proyecto.ip }}:~/{{ proyecto.name }}"
