---
- name: Desplegar en Pre-Produccion
  hosts: all
  become: yes

  tasks:    
  - name: Detener Apache 
    service:
      name: httpd
      state: stopped
       
     
  - name: remove directory
    file:
      path: /var/www/html/{{ proyecto.name }}/
      state: absent
       

  - name: Copiar directorio asignando owner y permisos
    copy:
      src: /web-public
      dest: /var/www/html/{{ proyecto.name }}/
      owner: apache
      group: apache
        

  - name: Arracar Apache
    service:
      name: httpd
      state: started    
