---
- hosts: all

  tasks:
  - name: Eliminacion de Snapshot de VM
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder: "/{{ datacenter_name }}/vm/"
      name: "{{ vm_name }}"
      snapshot_name: "{{ snap_name }}"
      state: absent
    delegate_to: localhost