---
- hosts: all

  tasks:
  - name: Eliminar todos los snapshots de VM
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder: "/{{ datacenter_name }}/vm/"
      name: "{{ vm_name }}"
      state: remove_all
    delegate_to: localhost
