---
- name: API Test  
  hosts: all

  tasks:
  - name: get json con el assetID
    uri:
      url: https://insightvm.cevaldom.local:3780/api/3/assets/search
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: yes
      validate_certs: no
      method: POST
      body: >
            {
             "filters": [
                  { 
                     "field": "host-name", 
                    "operator": "is", 
                    "value": "{{ ansible_nodename }}",
                  }
                ],
                "match": "all"
             }
      body_format: json
      status_code: 200
    delegate_to: localhost
    register: resultassetId
    
  - name: optener el asset id
    set_fact:
      assetId: "{{ resultassetId.json.resources[0].id }}"                         #jsondata: "{{ resultassetId.stdout | from_json }}"
      
  - name: Mostrar assetId
    debug: 
      msg: "El asset id es: {{ assetId }}"
      
##############################################################       
  - name: get json con Vulnerability
    uri:
      url: https://insightvm.cevaldom.local:3780/api/3/assets/{id}/vulnerabilities
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: yes
      validate_certs: no
      method: GET
      body_format: json
      status_code: 200
    delegate_to: localhost
    register: resultVulnerability
       
  - name: obteniendo Vulnerabilidad
    set_fact:
      VulnerabilityId: "{{ resultVulnerability.json.resources[0].id }}"     
     
  - name: Mostrar Vulnerabilidad
    debug: 
      msg: "La vulnerabilidad es: {{ VulnerabilityId }}"
     
##############################################################       
  - name: get json con solution
    uri:
      url: https://insightvm.cevaldom.local:3780/api/3/assets/{id}/vulnerabilities/{vulnerabilityId}/solution 
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: yes
      validate_certs: no
      method: GET
      body_format: json
      status_code: 200
    delegate_to: localhost
    register: resultsolution
 
  - name: obteniendo solution
    set_fact:     
      solution: "{{ resultsolution.json.resources[0].steps.text }}"     

  - name: Mostrar solution
    debug: 
      msg: "La solucion es: {{ solution }}"
      
  ##############################################################    
  
  - name: obteniendo comando
    set_fact:
      Comando: "{{ solution | regex_search('Use `(.+)`', '\\1') | first }}"      

  - name: Mostrar comando
    debug: 
      msg: "Comando a ejecutar: {{ Comando }}"      
       
  - name: cambiar comando 
    set_fact:
      Comando: "hostname"
      
  - name: Ejecutar solution, comando {{ Comando }}
    command: "{{ Comando }}"     
